[package]
name = "day_14"
version = "0.1.0"
authors = ["Rutger Claes <rgc@rgc.be>"]
edition = "2018"

[dependencies]
utils = { path = "../utils" }
im-rc = "15.0.0"
itertools = "0.9.0"
regex = "1.4.2"
lazy_static = "1.4.0"
pbr = "1.0.3"