[package]
name = "day_10"
version = "0.1.0"
authors = ["Rutger Claes <rgc@rgc.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
im-rc = "15.0.0"
itertools = "0.9.0"